# Reverse proxy
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    # depends_on:
    #   - NAME OF APP 


docker push chrleybolton/spring-boot-app:latest
